name: 'Deploy React code to GitHub Pages'
description: 'Build and deploy react code to GitHub pages'
branding:
  icon: upload-cloud
  color: red
inputs:
  checkout:
    description: 'Specifies if this action should checkout the code'
    required: false
    default: 'true'
outputs:
  page_url:
    description: "The URL of the page"
    value: ${{ steps.deploy.outputs.page_url }}

  

runs:
  using: 'composite'

  steps:
    - name: Checkout if required
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v3

    - name: 'Build'
      shell: bash
      run: |
        echo "::group::Build"
        npm ci
        npm run build
        echo "::endgroup::"

    - name: 'upload'
      uses: actions/upload-pages-artifact@v1.0.4
      with: 
        path: /dist

    - id: deploy
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ github.token }}
